version: '2'
services:
  master:
    build:
      context: ./jenkins-master
    restart: always
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes_from:
      - master_data
  master_data:
    image: busybox
    volumes:
      - /var/jenkins_home
    command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home"]
  worker:
    #image: eeacms/jenkins-slave-eea:2.0
    build:
      context: ./jenkins-slave
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - worker_data
    links:
      - master:master
    environment:
      - JAVA_OPTS=-Xmx2048m
      - JENKINS_NAME=worker
      - JENKINS_RETRY=10
    env_file:
      - .secret
  worker_data:
    image: busybox
    volumes:
      - /var/jenkins_home/worker
    command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home/worker"]
